"""empty message

Revision ID: 4e703e898f4c
Revises: 95306375f899
Create Date: 2018-07-05 21:52:57.083750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e703e898f4c'
down_revision = '95306375f899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=258), nullable=True))
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
