"""empty message

Revision ID: 95306375f899
Revises: 4dd2c1bc0881
Create Date: 2018-07-05 20:12:03.512190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95306375f899'
down_revision = '4dd2c1bc0881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###
